/*
 * Prowlarr
 *
 * Prowlarr API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BookSearchParam {
    #[serde(rename = "q")]
    Q,
    #[serde(rename = "title")]
    Title,
    #[serde(rename = "author")]
    Author,
    #[serde(rename = "publisher")]
    Publisher,
    #[serde(rename = "genre")]
    Genre,
    #[serde(rename = "year")]
    Year,

}

impl std::fmt::Display for BookSearchParam {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Q => write!(f, "q"),
            Self::Title => write!(f, "title"),
            Self::Author => write!(f, "author"),
            Self::Publisher => write!(f, "publisher"),
            Self::Genre => write!(f, "genre"),
            Self::Year => write!(f, "year"),
        }
    }
}

impl Default for BookSearchParam {
    fn default() -> BookSearchParam {
        Self::Q
    }
}

