/*
 * Prowlarr
 *
 * Prowlarr API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexerStatistics {
    #[serde(rename = "indexerId", skip_serializing_if = "Option::is_none")]
    pub indexer_id: Option<i32>,
    #[serde(rename = "indexerName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub indexer_name: Option<Option<String>>,
    #[serde(rename = "averageResponseTime", skip_serializing_if = "Option::is_none")]
    pub average_response_time: Option<i32>,
    #[serde(rename = "averageGrabResponseTime", skip_serializing_if = "Option::is_none")]
    pub average_grab_response_time: Option<i32>,
    #[serde(rename = "numberOfQueries", skip_serializing_if = "Option::is_none")]
    pub number_of_queries: Option<i32>,
    #[serde(rename = "numberOfGrabs", skip_serializing_if = "Option::is_none")]
    pub number_of_grabs: Option<i32>,
    #[serde(rename = "numberOfRssQueries", skip_serializing_if = "Option::is_none")]
    pub number_of_rss_queries: Option<i32>,
    #[serde(rename = "numberOfAuthQueries", skip_serializing_if = "Option::is_none")]
    pub number_of_auth_queries: Option<i32>,
    #[serde(rename = "numberOfFailedQueries", skip_serializing_if = "Option::is_none")]
    pub number_of_failed_queries: Option<i32>,
    #[serde(rename = "numberOfFailedGrabs", skip_serializing_if = "Option::is_none")]
    pub number_of_failed_grabs: Option<i32>,
    #[serde(rename = "numberOfFailedRssQueries", skip_serializing_if = "Option::is_none")]
    pub number_of_failed_rss_queries: Option<i32>,
    #[serde(rename = "numberOfFailedAuthQueries", skip_serializing_if = "Option::is_none")]
    pub number_of_failed_auth_queries: Option<i32>,
}

impl IndexerStatistics {
    pub fn new() -> IndexerStatistics {
        IndexerStatistics {
            indexer_id: None,
            indexer_name: None,
            average_response_time: None,
            average_grab_response_time: None,
            number_of_queries: None,
            number_of_grabs: None,
            number_of_rss_queries: None,
            number_of_auth_queries: None,
            number_of_failed_queries: None,
            number_of_failed_grabs: None,
            number_of_failed_rss_queries: None,
            number_of_failed_auth_queries: None,
        }
    }
}

