/*
 * Prowlarr
 *
 * Prowlarr API docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagDetailsResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "notificationIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "indexerIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub indexer_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "indexerProxyIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub indexer_proxy_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "applicationIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub application_ids: Option<Option<Vec<i32>>>,
}

impl TagDetailsResource {
    pub fn new() -> TagDetailsResource {
        TagDetailsResource {
            id: None,
            label: None,
            notification_ids: None,
            indexer_ids: None,
            indexer_proxy_ids: None,
            application_ids: None,
        }
    }
}

